function plot_commands( fdet )
% plot general commands
%
% PLOT_COMMANDS( fdet )
%
% INPUT
% fdet : detected labels flag (scalar logical)

		% safeguard
	if nargin < 1 || ~isscalar( fdet ) || ~islogical( fdet )
		error( 'invalid argument: fdet' );
	end

		% plot general commands
	style = xis.hStyle.instance();

	s = { ...
		'GENERAL COMMANDS', ...
		'', ...
		'PAGEDOWN/UP: +/- 1 trial' ...
		'SHIFT+PAGEDOWN/UP: +/- 10 trials', ...
		'CONTROL+PAGEDOWN/UP: +/- 100 trials', ...
		'HOME/END: first/last trial', ...
		'', ...
		'RETURN: playback audio', ...
		'', ...
		'S: toggle decibel scale', ...
		'', ...
		'CONTROL+TAB: toggle detection view', ...
		'', ...
		'ESCAPE: quit' };

	pos = 1/3;
	if fdet
		pos = 2/3;
	end

	annotation( 'textbox', [pos, 0, 1/3, 1/4], 'String', s, ...
		'BackgroundColor', style.color( 'grey', style.scale( -1/9 ) ) );

end

