function plot_cmds()
% plot commands
%
% PLOT_CMDS()

		% plot commands
	s = { ...
		'COMMANDS', ...
		'', ...
		'PAGEDOWN/UP: +/- 1 trial' ...
		'SHIFT+PAGEDOWN/UP: +/- 10 trials', ...
		'CONTROL+PAGEDOWN/UP: +/- 100 trials', ...
		'HOME/END: first/last trial', ...
		'', ...
		'RETURN: playback audio', ...
		'', ...
		'D: toggle decibel scale', ...
		'', ...
		'ESCAPE: quit' };

	annotation( 'textbox', [2/3, 0, 1/3, 1/4], 'String', s );

end

