function plot_commands( labmode )
% plot commands
%
% PLOT_COMMANDS( labmode )
%
% INPUT
% labmode : labeling mode [activity | landmarks | formants] (row char)

		% safeguard
	if nargin < 1 || ~isrow( labmode ) || ~ischar( labmode )
		error( 'invalid argument: labmode' );
	end

		% plot commands
	s = { ...
		'GENERAL COMMANDS', ...
		'', ...
		'SPACE: next unlabeled trial', ...
		'PAGEDOWN/UP: +/- 1 trial' ...
		'SHIFT+PAGEDOWN/UP: +/- 10 trials', ...
		'CONTROL+PAGEDOWN/UP: +/- 100 trials', ...
		'HOME/END: first/last trial', ...
		'', ...
		'RETURN: playback audio', ...
		'', ...
		'D: toggle decibel scale', ...
		'', ...
		'CONTROL+BACKSPACE: clear trial mode labels', ...
		'SHIFT+CONTROL+ALT+BACKSPACE: clear run mode labels', ...
		'', ...
		'ESCAPE: save and quit' };

	annotation( 'textbox', [1/3, 0, 1/3, 1/4], 'String', s );

	switch labmode % mode commands
		case 'activity'
			s = { ...
				'MODE COMMANDS', ...
				'', ...
				'K: set ''ka'' class', ...
				'T: set ''ta'' class', ...
				'', ...
				'LEFT: set activity start', ...
				'RIGHT: set activity stop', ...
				'', ...
				'SHIFT+RETURN: playback activity' };

		case 'landmarks'
			s = { ...
				'MODE COMMANDS', ...
				'', ...
				'L: set landmarks (3 clicks, RETURN cancels)', ...
				'', ...
				'B: set burst onset (1 click, RETURN cancels)', ...
				'V: set voice onset (1 click, RETURN cancels)', ...
				'R: set voice release (1 click, RETURN cancels)', ...
				'', ...
				'LEFT: detail landmark', ...
				'', ...
				'SHIFT+RETURN: playback from burst' };

		case 'formants'
			s = { ...
				'MODE COMMANDS', ...
				'', ...
				'LEFT: set F0 onset', ...
				'', ...
				'F: set formant onsets (3 clicks, RETURN cancels)', ...
				'1: set F1 onset (1 click, RETURN cancels)', ...
				'2: set F2 onset (1 click, RETURN cancels)', ...
				'3: set F3 onset (1 click, RETURN cancels)', ...
				'', ...
				'B: toggle blending' };

		otherwise
			error( 'invalid argument: labmode' );
	end

	annotation( 'textbox', [2/3, 0, 1/3, 1/4], 'String', s );

end

